name: Docs master

on:
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: drewrh/zone-theorem@master
      with:
        docs-folder: "docs/"
